### PR TITLE
have some Sodium 0.5.2

### PR DESCRIPTION
**Pull request by IMS212**
also Iris 1.6.8 i guess?

### CODE REVIEW

**Comment by skunkmommy** [comment]
YES PLEASE

**Comment by skunkmommy** [comment]
can u send the jar? i dont think this repo has actions or whatever, and yours doesnt have one either - it has one but thats like a year old so obviously not what i want

**Comment by IMS212** [comment]
This will not magically let you run Create.

**Comment by PepperCode1** [comment]
This will be unnecessary and conflict once Forge branches are merged into Fabric branches. Commit bc4fd1e updated Rubidium compatibility to >0.7.0 and will work without changes on Fabric, allowing Flywheel to be compatible with Sodium >0.5.0.

**Comment by NolanHewitt** [comment]
> This will be unnecessary and conflict once Forge branches are merged into Fabric branches. Commit [bc4fd1e](https://github.com/Jozufozu/Flywheel/commit/bc4fd1e95524347ae851b67bd80b0185e7bef8b9) updated Rubidium compatibility to >0.7.0 and will work without changes on Fabric, allowing Flywheel to be compatible with Sodium >0.5.0.

Any word on when that will happen?

**Pull request closed without merging**
