### PR TITLE
1.20 0.6.10

### PR DESCRIPTION
**Pull request by IThundxr**
Patch taken from https://github.com/IMS212/Flywheel merge120 branch

Thanks to @IMS212 for the hard work, just making the PR so its easier to merge.

### CODE REVIEW

**Comment by AwesomeDude091** [comment]
🎉

**Comment by IThundxr** [comment]
@PepperCode1 Could you review this and lmk if there's any changes you want me to make?

**Review by AwesomeDude091 — APPROVED** [review]
I know I have no power, but I approve lol

**Comment by vovamod** [comment]
Seems pretty neat I say

**Review by vovamod — APPROVED** [review]

**Review by kaiyga — APPROVED** [review]
I've been waiting for this for quite a long time. I'm so happy someone finally did this

**Review by anioji — APPROVED** [review]
So good. This should have been done a long time ago

**Comment by goteusz-maszyk** [comment]
@Jozufozu why don't you merge it?

**Comment by Poopooracoocoo** [comment]
@goteusz-maszyk see https://github.com/Jozufozu/Flywheel/pull/214#issuecomment-1839197540

**Comment by goteusz-maszyk** [comment]
Ah ok, so PepperCode is just away (or busy)...

**Comment by Dragon-Seeker** [comment]
@PepperCode1 Any update to this PR being Merged. Seems quite crucial and has been sitting for quite some time.

**Comment by goteusz-maszyk** [comment]
@PepperCode1 The PR is waiting since half of November. It's been 2 months since then. What's going on?

**Review by pauliesnug — APPROVED** [review]
lgtm! why isn't this getting merged into the release schedule? there are no conflicts.

**Pull request merged**
