### PR TITLE
Architectury Multi-Loader Setup

### PR DESCRIPTION
**Pull request by Kneelawk**
# This PR

This PR merges the Flywheel Fabric and Forge branches into a single branch, using an Architectury-based multi-project setup.

### CODE REVIEW

**Comment by Jozufozu** [comment]
Is the jsr dependency necessary for other dependencies? We use jetbrains annotations for all immediate flywheel stuff

**Comment by Kneelawk** [comment]
> Is the jsr dependency necessary for other dependencies? We use jetbrains annotations for all immediate flywheel stuff

The jsr is the only place I could find the `javax.annotation.ParametersAreNonnullByDefault` annotation generated in the package-infos, but I can look again.

**Review by Jozufozu — APPROVED** [review]
Everything seems good to me

**Review by Jozufozu — APPROVED** [review]
There are still some unused Gradle tasks to clean up but I think this should merge to unblock more crucial tasks.

**Review by PepperCode1 — APPROVED** [review]

**Pull request merged**
